[build]
  publish = "docs/.vuepress/dist"
  command = "node ./node_modules/@vuepress/cli/index.js build docs"
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "v10.13.0"
  YARN_VERSION = "1.12.1"
