---
new_page_extension: md
auto_deploy: true
admin_path: docs/.vuepress/public/admin
webhook_url: 
sections:
- type: directory
  path: ''
  label: Not Posts
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - post
- type: directory
  path: docs
  label: Posts
  create: documents
  match: "**/*.md"
  templates:
  - post
upload_dir: docs/.vuepress/public
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: 'images/:filename:'
build:
  preview_command: yarn docs:build
  publish_command: yarn docs:build
  output_directory: docs/.vuepress/dist
