---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs
  label: what
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  publish_command: yarn docs:build
  output_directory: docs/.vuepress/dist
