---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs
  label: All Docs
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: public
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: 'images/:filename:'
build:
  preview_command: yarn docs:build
  publish_command: yarn docs:build
  output_directory: docs/.vuepress/dist
